on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  drata-iac-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Drata Action
        uses: drata/compliance-as-code-action@v0.0.102
        env:
            DRATA_API_TOKEN: ${{ secrets.DRATA_IAC_PIPELINE_KEY }}
            GITHUB_REPOSITORY: $GITHUB_REPOSITORY
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            minimumSeverity: 'CRITICAL'
            - name: Drata Compliance as Code Action
  # You may pin to the exact commit or the version.
  # uses: drata/compliance-as-code-action@a3085e633f315132c8fe1b5e7e9c40be1c01964c
  uses: drata/compliance-as-code-action@v1.0.0
  with:
    # Minimum severity
    minimumSeverity: # default is Critical
    # Workspace to run this action for
    workspaceId: # optional, default is 1
    # A boolean flag that notes if design gaps should be displayed in GitHub Workflow console log
    verboseLogging: # optional
    # Provide your region EU, US
    region: # optional, default is US
    # Time in seconds to wait for testing to complete before initiating a timeout of the action.
    timeoutSeconds: # optional, default is 600
          
