on:
  push:
    branches: 
      - compliance/**
  pull_request:
    branches: 
      - main

jobs:
  drata-iac-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Drata Action
        uses: drata/compliance-as-code-action@v0.0.102
        env:
            DRATA_API_TOKEN: ${{ secrets.3e08de8c-1abc-4324-80d7-ce6ac4355c8b }}
            GITHUB_REPOSITORY: $GITHUB_REPOSITORY
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            minimumSeverity: 'LOW'
      
  
          
